### ISSUE TITLE
Pricing cards don't render properly on Firefox

### ISSUE THREAD

**Issue by PratikGarai** [hellomohitsangwan/ms#1]
## Problem 
<a href="https://hellomohitsangwan.github.io/ms/services.html">URL</a>
The pricing cards don't work properly on Firefox browser. On Firefox : 
![image](https://user-images.githubusercontent.com/58355527/126839450-b92c7861-0801-40db-9a48-513fc5fec869.png)

On Chrome however, it seems to work fine:
![image](https://user-images.githubusercontent.com/58355527/126839704-2137e9b9-ae00-44bb-86ad-ce0c2df79d76.png)

## Suggested edit : 
Use the css styling property
```css
.pricing-card-back {
  backface-visibility: hidden;
}
```
This will allow the two face characteristic to work properly on Firefox and also won't hurt the working in Chrome.

**Comment by PratikGarai** [comment]
## Proof of solution
![image](https://user-images.githubusercontent.com/58355527/126840283-ff04506e-9c46-4d63-9b56-5b189e6cb8c0.png)

I added the property using the developer tools and it works fine 😀

**Comment by hellomohitsangwan** [comment]
thanks Pratik, glad you noticed that and informed me

 now it's resolved
